-- Oracle AI Database 26ai schema for the medical classifier POC.
-- IDs are generated by the application as UUID/ULID strings.
-- Adjust VECTOR dimensions/index parameters to the configured embedding model.

CREATE TABLE uploads (
  upload_id              VARCHAR2(64) PRIMARY KEY,
  original_filename      VARCHAR2(1024) NOT NULL,
  source_object_path     VARCHAR2(2048) NOT NULL,
  checksum_sha256        VARCHAR2(64) NOT NULL,
  byte_size              NUMBER(19) NOT NULL,
  page_count             NUMBER(10),
  state                   VARCHAR2(40) NOT NULL,
  current_stage           VARCHAR2(100),
  supplied_metadata       JSON,
  created_at              TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at              TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uploads_state_ck CHECK (
    state IN (
      'received', 'stored', 'splitting_pages', 'processing_pages',
      'assembling_documents', 'classifying_documents', 'indexing',
      'ready', 'ready_with_warnings', 'failed'
    )
  )
);

-- System-owned reference works are deliberately separate from user uploads.
-- They are loaded by the reference dataloader and never enter the PDF queues.
CREATE TABLE reference_sources (
  reference_source_id     VARCHAR2(64) PRIMARY KEY,
  name                    VARCHAR2(255) NOT NULL UNIQUE,
  source_kind             VARCHAR2(40) NOT NULL,
  version                 VARCHAR2(128) NOT NULL,
  source_object_path      VARCHAR2(2048) NOT NULL,
  checksum_sha256         VARCHAR2(64) NOT NULL,
  byte_size               NUMBER(19) NOT NULL,
  state                   VARCHAR2(40) NOT NULL,
  node_count              NUMBER(19) DEFAULT 0 NOT NULL,
  edge_count              NUMBER(19) DEFAULT 0 NOT NULL,
  fragment_count          NUMBER(19) DEFAULT 0 NOT NULL,
  metadata                JSON,
  created_at              TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at              TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT reference_sources_kind_ck CHECK (
    source_kind IN ('knowledge_graph', 'corpus')
  ),
  CONSTRAINT reference_sources_state_ck CHECK (
    state IN ('registered', 'importing', 'indexing', 'ready', 'failed')
  )
);

CREATE TABLE reference_import_runs (
  reference_import_run_id VARCHAR2(64) PRIMARY KEY,
  reference_source_id     VARCHAR2(64) NOT NULL REFERENCES reference_sources(reference_source_id),
  checksum_sha256         VARCHAR2(64) NOT NULL,
  state                   VARCHAR2(40) NOT NULL,
  error_message           CLOB,
  started_at              TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  completed_at            TIMESTAMP WITH TIME ZONE,
  CONSTRAINT reference_import_runs_state_ck CHECK (
    state IN ('importing', 'ready', 'failed')
  )
);

-- Durable, asynchronous agent conversations.  The API only creates/polls these
-- rows; a private worker claims the job and records its observable activity.
-- Raw model output, the deterministic result, and the optional formatter result
-- are deliberately retained separately for auditability.
CREATE TABLE agent_conversations (
  conversation_id          VARCHAR2(64) PRIMARY KEY,
  idempotency_key          VARCHAR2(255),
  request_hash             VARCHAR2(64),
  question                 CLOB NOT NULL,
  source_scope             VARCHAR2(20) DEFAULT 'all' NOT NULL,
  upload_ids               JSON,
  reference_source_ids     JSON,
  state                    VARCHAR2(20) DEFAULT 'queued' NOT NULL,
  transform_state          VARCHAR2(20) DEFAULT 'not_requested' NOT NULL,
  orchestrator_model       VARCHAR2(255),
  formatter_model          VARCHAR2(255),
  raw_answer               CLOB,
  result_data              JSON,
  transformed_answer       JSON,
  error_message            CLOB,
  attempt_count            NUMBER(10) DEFAULT 0 NOT NULL,
  worker_id                VARCHAR2(128),
  lease_expires_at         TIMESTAMP WITH TIME ZONE,
  next_event_seq           NUMBER(19) DEFAULT 1 NOT NULL,
  created_at               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  started_at               TIMESTAMP WITH TIME ZONE,
  completed_at             TIMESTAMP WITH TIME ZONE,
  updated_at               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT agent_conversations_scope_ck CHECK (
    source_scope IN ('documents', 'references', 'all')
  ),
  CONSTRAINT agent_conversations_state_ck CHECK (
    state IN ('queued', 'running', 'completed', 'blocked', 'failed')
  ),
  CONSTRAINT agent_conversations_transform_ck CHECK (
    transform_state IN ('not_requested', 'queued', 'running', 'completed', 'failed')
  ),
  CONSTRAINT agent_conversations_idempotency_uq UNIQUE (idempotency_key)
);

CREATE INDEX agent_conversations_state_ix
  ON agent_conversations(state, created_at);
CREATE INDEX agent_conversations_transform_ix
  ON agent_conversations(transform_state, updated_at);

-- Events are append-only and monotonically ordered within one conversation.
-- Event payloads contain bounded operational summaries, never hidden model
-- chain-of-thought or complete retrieved documents.
CREATE TABLE agent_events (
  event_id                 VARCHAR2(64) PRIMARY KEY,
  conversation_id          VARCHAR2(64) NOT NULL
                             REFERENCES agent_conversations(conversation_id),
  event_seq                NUMBER(19) NOT NULL,
  event_type               VARCHAR2(100) NOT NULL,
  event_data               JSON,
  created_at               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT agent_events_sequence_uq UNIQUE (conversation_id, event_seq)
);

CREATE INDEX agent_events_conversation_ix
  ON agent_events(conversation_id, event_seq);

CREATE TABLE processing_runs (
  processing_run_id       VARCHAR2(64) PRIMARY KEY,
  upload_id               VARCHAR2(64) NOT NULL REFERENCES uploads(upload_id),
  processor               VARCHAR2(255) NOT NULL,
  processor_version       VARCHAR2(255) NOT NULL,
  model_manifest          JSON,
  state                    VARCHAR2(40) NOT NULL,
  started_at               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  completed_at             TIMESTAMP WITH TIME ZONE
);

CREATE TABLE nodes (
  node_id                  VARCHAR2(64) PRIMARY KEY,
  node_type                VARCHAR2(40) NOT NULL,
  upload_id                VARCHAR2(64) REFERENCES uploads(upload_id),
  reference_source_id      VARCHAR2(64) REFERENCES reference_sources(reference_source_id),
  processing_run_id        VARCHAR2(64) REFERENCES processing_runs(processing_run_id),
  ordinal                  NUMBER(10),
  status                   VARCHAR2(20) NOT NULL,
  object_path              VARCHAR2(2048),
  media_type               VARCHAR2(255),
  checksum_sha256          VARCHAR2(64),
  byte_size                NUMBER(19),
  structural_data          JSON,
  created_at               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT nodes_type_ck CHECK (
    node_type IN (
      'upload', 'processing_run', 'child_document', 'page', 'fragment',
      'text_block', 'paragraph', 'table', 'table_cell', 'key_value', 'image',
      'reference_entity', 'reference_document', 'reference_chunk'
    )
  ),
  CONSTRAINT nodes_owner_ck CHECK (
    (upload_id IS NOT NULL AND reference_source_id IS NULL) OR
    (upload_id IS NULL AND reference_source_id IS NOT NULL)
  ),
  CONSTRAINT nodes_status_ck CHECK (
    status IN ('queued', 'processing', 'provisional', 'ready', 'failed')
  )
);

CREATE INDEX nodes_upload_ix ON nodes(upload_id, node_type, status);
CREATE INDEX nodes_reference_ix ON nodes(reference_source_id, node_type, status);
CREATE INDEX nodes_run_ix ON nodes(processing_run_id, node_type);

-- Reference graphs commonly repeat a very small relationship vocabulary over
-- millions of edges. Store each definition once instead of repeating JSON keys
-- and provenance on every edge row.
CREATE TABLE reference_edge_types (
  reference_edge_type_id   NUMBER(15) PRIMARY KEY,
  reference_source_id      VARCHAR2(64) NOT NULL
                              REFERENCES reference_sources(reference_source_id),
  predicate                VARCHAR2(255) NOT NULL,
  display_relation         VARCHAR2(255),
  CONSTRAINT reference_edge_types_uq UNIQUE (
    reference_source_id, predicate, display_relation
  )
);

CREATE TABLE edges (
  edge_id                  VARCHAR2(64) PRIMARY KEY,
  source_node_id           VARCHAR2(64) NOT NULL REFERENCES nodes(node_id),
  target_node_id           VARCHAR2(64) NOT NULL REFERENCES nodes(node_id),
  relationship_type        VARCHAR2(20) NOT NULL,
  processing_run_id        VARCHAR2(64) REFERENCES processing_runs(processing_run_id),
  confidence               NUMBER(5,4),
  reference_edge_type_id   NUMBER(15)
                              REFERENCES reference_edge_types(reference_edge_type_id),
  edge_data                JSON,
  created_at               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT edges_relationship_ck CHECK (
    relationship_type IN (
      'CONTAINS', 'DERIVED_FROM', 'HAS_FRAGMENT', 'RELATED_TO',
      'MENTIONS', 'MAPS_TO', 'SUPPORTED_BY'
    )
  ),
  CONSTRAINT edges_confidence_ck CHECK (
    confidence IS NULL OR confidence BETWEEN 0 AND 1
  ),
  CONSTRAINT edges_unique_uq UNIQUE (
    source_node_id, target_node_id, relationship_type, processing_run_id
  )
);

-- Idempotent upgrade for databases whose edges table predates normalized
-- reference relationship definitions.
DECLARE
  column_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO column_count
    FROM user_tab_columns
   WHERE table_name = 'EDGES'
     AND column_name = 'REFERENCE_EDGE_TYPE_ID';
  IF column_count = 0 THEN
    EXECUTE IMMEDIATE
      'ALTER TABLE edges ADD (reference_edge_type_id NUMBER(15) '
      || 'REFERENCES reference_edge_types(reference_edge_type_id))';
  END IF;
END;
/

CREATE INDEX edges_source_ix ON edges(source_node_id, relationship_type);
CREATE INDEX edges_target_ix ON edges(target_node_id, relationship_type);

CREATE TABLE labels (
  label_id                 VARCHAR2(64) PRIMARY KEY,
  label_key                VARCHAR2(255) NOT NULL UNIQUE,
  display_name             VARCHAR2(512) NOT NULL,
  seeded                   NUMBER(1) DEFAULT 0 NOT NULL,
  created_by_processor     VARCHAR2(255),
  created_at               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT labels_seeded_ck CHECK (seeded IN (0, 1))
);

CREATE TABLE node_labels (
  node_label_id            VARCHAR2(64) PRIMARY KEY,
  node_id                  VARCHAR2(64) NOT NULL REFERENCES nodes(node_id),
  label_id                 VARCHAR2(64) NOT NULL REFERENCES labels(label_id),
  processing_run_id        VARCHAR2(64) REFERENCES processing_runs(processing_run_id),
  confidence               NUMBER(5,4),
  processor                VARCHAR2(255),
  processor_version        VARCHAR2(255),
  evidence_node_id         VARCHAR2(64) REFERENCES nodes(node_id),
  created_at               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT node_labels_confidence_ck CHECK (
    confidence IS NULL OR confidence BETWEEN 0 AND 1
  ),
  CONSTRAINT node_labels_unique_uq UNIQUE (node_id, label_id, processing_run_id)
);

CREATE INDEX node_labels_label_ix ON node_labels(label_id, confidence);
CREATE INDEX node_labels_node_ix ON node_labels(node_id);

CREATE TABLE node_attributes (
  attribute_id             VARCHAR2(64) PRIMARY KEY,
  node_id                  VARCHAR2(64) NOT NULL REFERENCES nodes(node_id),
  processing_run_id        VARCHAR2(64) REFERENCES processing_runs(processing_run_id),
  attribute_name           VARCHAR2(512) NOT NULL,
  value_type               VARCHAR2(20) NOT NULL,
  string_value             CLOB,
  number_value             NUMBER,
  date_value               TIMESTAMP WITH TIME ZONE,
  boolean_value            NUMBER(1),
  json_value               JSON,
  confidence               NUMBER(5,4),
  source_kind              VARCHAR2(20) NOT NULL,
  assertion_kind           VARCHAR2(20),
  processor                VARCHAR2(255),
  processor_version        VARCHAR2(255),
  evidence_node_id         VARCHAR2(64) REFERENCES nodes(node_id),
  created_at               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT node_attributes_type_ck CHECK (
    value_type IN ('string', 'number', 'date', 'boolean', 'json')
  ),
  CONSTRAINT node_attributes_source_ck CHECK (
    source_kind IN ('upload', 'extracted', 'inferred', 'system')
  ),
  CONSTRAINT node_attributes_assertion_ck CHECK (
    assertion_kind IS NULL OR assertion_kind IN ('explicit', 'inferred', 'unknown')
  ),
  CONSTRAINT node_attributes_boolean_ck CHECK (
    boolean_value IS NULL OR boolean_value IN (0, 1)
  ),
  CONSTRAINT node_attributes_confidence_ck CHECK (
    confidence IS NULL OR confidence BETWEEN 0 AND 1
  )
);

CREATE INDEX node_attributes_name_ix
  ON node_attributes(attribute_name, node_id);

CREATE TABLE fragments (
  fragment_id              VARCHAR2(64) PRIMARY KEY,
  node_id                  VARCHAR2(64) NOT NULL REFERENCES nodes(node_id),
  source_page_node_id      VARCHAR2(64) REFERENCES nodes(node_id),
  source_document_node_id  VARCHAR2(64) REFERENCES nodes(node_id),
  fragment_type            VARCHAR2(100) NOT NULL,
  fragment_text            CLOB,
  normalized_text          CLOB,
  bounding_box             JSON,
  confidence               NUMBER(5,4),
  processor                VARCHAR2(255),
  processor_version        VARCHAR2(255),
  created_at               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fragments_confidence_ck CHECK (
    confidence IS NULL OR confidence BETWEEN 0 AND 1
  )
);

-- Oracle Text is case-insensitive by default, so indexing the canonical text
-- avoids storing a second lower-cased CLOB. The block also migrates databases
-- created by earlier builds where this index targeted normalized_text.
DECLARE
  indexed_column VARCHAR2(128);
BEGIN
  SELECT MAX(column_name)
    INTO indexed_column
    FROM user_ind_columns
   WHERE index_name = 'FRAGMENTS_TEXT_IX';

  IF indexed_column IS NOT NULL AND indexed_column <> 'FRAGMENT_TEXT' THEN
    EXECUTE IMMEDIATE 'DROP INDEX fragments_text_ix FORCE';
    indexed_column := NULL;
  END IF;

  IF indexed_column IS NULL THEN
    EXECUTE IMMEDIATE
      'CREATE INDEX fragments_text_ix ON fragments(fragment_text) '
      || 'INDEXTYPE IS CTXSYS.CONTEXT';
  END IF;
END;
/

CREATE TABLE embeddings (
  embedding_id             VARCHAR2(64) PRIMARY KEY,
  node_id                  VARCHAR2(64) NOT NULL REFERENCES nodes(node_id),
  fragment_id              VARCHAR2(64) REFERENCES fragments(fragment_id),
  embedding_model          VARCHAR2(255) NOT NULL,
  embedding_version        VARCHAR2(255) NOT NULL,
  source_text              CLOB,
  embedding                VECTOR(*, FLOAT32) NOT NULL,
  created_at               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

-- Example only. Select organization/accuracy parameters after representative POC testing.
CREATE VECTOR INDEX embeddings_vector_ix
  ON embeddings(embedding)
  ORGANIZATION NEIGHBOR PARTITIONS
  DISTANCE COSINE
  WITH TARGET ACCURACY 90;

CREATE TABLE artifacts (
  artifact_id              VARCHAR2(64) PRIMARY KEY,
  node_id                  VARCHAR2(64) NOT NULL REFERENCES nodes(node_id),
  artifact_role            VARCHAR2(20) NOT NULL,
  object_path              VARCHAR2(2048) NOT NULL,
  media_type               VARCHAR2(255) NOT NULL,
  byte_size                NUMBER(19) NOT NULL,
  checksum_sha256          VARCHAR2(64) NOT NULL,
  created_at               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT artifacts_role_ck CHECK (
    artifact_role IN ('original', 'pdf', 'image', 'thumbnail', 'text', 'json')
  )
);

CREATE INDEX artifacts_node_ix ON artifacts(node_id, artifact_role);

-- Consolidated object storage: binary payloads (upload originals, page PDFs,
-- rendered images, extracted text/JSON) live in SecureFiles BLOBs keyed by the
-- same object_path used elsewhere in the schema. Used by DatabaseStorage.
CREATE TABLE object_store (
  object_key               VARCHAR2(2048) PRIMARY KEY,
  media_type               VARCHAR2(255) NOT NULL,
  byte_size                NUMBER(19) NOT NULL,
  checksum_sha256          VARCHAR2(64) NOT NULL,
  file_data                BLOB NOT NULL,
  created_at               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
) LOB (file_data) STORE AS SECUREFILES (COMPRESS HIGH);


CREATE TABLE processing_failures (
  failure_id               VARCHAR2(64) PRIMARY KEY,
  upload_id                VARCHAR2(64) NOT NULL REFERENCES uploads(upload_id),
  processing_run_id        VARCHAR2(64) REFERENCES processing_runs(processing_run_id),
  node_id                  VARCHAR2(64) REFERENCES nodes(node_id),
  stage                    VARCHAR2(100) NOT NULL,
  error_code               VARCHAR2(100),
  error_message            CLOB NOT NULL,
  error_context            JSON,
  source_artifact_node_id  VARCHAR2(64) REFERENCES nodes(node_id),
  occurred_at              TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX processing_failures_upload_ix
  ON processing_failures(upload_id, occurred_at);

-- The relationship type is an edge property so one constrained edge table can
-- represent all three POC relationships. Queries must filter relationship_type.
CREATE PROPERTY GRAPH medical_document_graph
  VERTEX TABLES (
    nodes
      KEY (node_id)
      LABEL node
      PROPERTIES (
        node_id,
        node_type,
        upload_id,
        reference_source_id,
        processing_run_id,
        ordinal,
        status,
        object_path,
        media_type,
        created_at
      )
  )
  EDGE TABLES (
    edges
      KEY (edge_id)
      SOURCE KEY (source_node_id) REFERENCES nodes (node_id)
      DESTINATION KEY (target_node_id) REFERENCES nodes (node_id)
      LABEL relation
      PROPERTIES (
        edge_id,
        relationship_type,
        processing_run_id,
        confidence,
        created_at
      )
  );

-- Example traversal: find child documents and uploads related to a fragment.
--
-- SELECT *
-- FROM GRAPH_TABLE (
--   medical_document_graph
--   MATCH (start_node IS node)-[e IS relation]->{1,3}(related IS node)
--   WHERE start_node.node_id = :fragment_node_id
--     AND e.relationship_type IN ('DERIVED_FROM', 'HAS_FRAGMENT', 'CONTAINS')
--   COLUMNS (
--     related.node_id AS node_id,
--     related.node_type AS node_type,
--     related.status AS status
--   )
-- );

-- Transactional Event Queues (TxEQ / Advanced Queuing) back the OracleQueue
-- adapter. One RAW-payload queue table holds all pipeline stage queues; each
-- CHANNEL in queue.py maps to a "<channel>_queue".
DECLARE
  object_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO object_count
    FROM user_queue_tables
   WHERE queue_table = 'MC_QUEUE_TABLE';

  IF object_count = 0 THEN
    DBMS_AQADM.CREATE_QUEUE_TABLE(
      queue_table        => 'mc_queue_table',
      queue_payload_type => 'RAW',
      multiple_consumers => FALSE
    );
  END IF;

  FOR q IN (
    SELECT column_value AS queue_name FROM TABLE(sys.dbms_debug_vc2coll(
      'page_split_queue',
      'page_process_queue',
      'document_assemble_queue',
      'index_queue',
      'agent_run_queue',
      'agent_transform_queue'
    ))
  ) LOOP
    SELECT COUNT(*) INTO object_count
      FROM user_queues
     WHERE name = UPPER(q.queue_name);

    IF object_count = 0 THEN
      DBMS_AQADM.CREATE_QUEUE(
        queue_name  => q.queue_name,
        queue_table => 'mc_queue_table'
      );
      DBMS_AQADM.START_QUEUE(queue_name => q.queue_name);
    END IF;
  END LOOP;
END;
/
